---
- name: Include RedHat setup tasks
  ansible.builtin.include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian setup tasks
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  ansible.builtin.package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"

- name: Ensure Kibana is started and enabled at boot.
  ansible.builtin.service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  ansible.builtin.template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart kibana
